Add total duration for unplayed items.
UniversityRadioYork/WebStudio pull request #178
Opened 2020-10-27 23:44 UTC by mstratford

2020-10-27 23:45 UTC, markspolakovs requested changes

2020-10-27 23:45 UTC, markspolakovs commented on src/showplanner/Player.tsx
> +  var channel_unplayed: number = 0;
* camelCase
* no need for explicit typedef

2020-10-27 23:45 UTC, markspolakovs commented on src/showplanner/Player.tsx
> +          &nbsp;Un-played: {secToHHMM(channel_unplayed)}
but y tho

2020-10-27 23:55 UTC, mstratford commented on src/showplanner/Player.tsx
> +          &nbsp;Un-played: {secToHHMM(channel_unplayed)}
It was ignoring spaces. Corrected now.

2020-10-27 23:58 UTC, markspolakovs approved these changes
I mean the "but y tho" was more about the entire concept of the PR - but sure, feature-creep away :p

2020-10-28 00:00 UTC, mstratford commented
> I mean the "but y tho" was more about the entire concept of the PR - but sure, feature-creep away :p

Idea was that if you needed to know how much music you have left to play during your show :)

2020-10-28 00:00 UTC, merged